steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Upgrading pip..."
        python -m pip install --upgrade pip
        echo "Installing dependencies..."
        pip install -r requirements.txt
        echo "Running pipeline script..."
        python pipeline.py
        

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 4800s
